config/routes.rb
DistinctionsFines::Application.routes.draw do

  resources :authentications

    match '/signout' => 'sessions#destroy', :as => :signout
    match '/signin' => 'sessions#new', :as => :signin
    match '/users/auth/:provider/callback' => 'authentications#create'          
    match '/auth/failure' => 'sessions#failure'

  devise_for :users, :controllers => { :omniauth_callbacks => "authentications"}

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :users

  resources :articles
  
  resources :comments  
  

  root :to => 'blog#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope :order => 'created_at ASC'

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
  
  validates :user, :title, :comment, :commentable, :presence => true
  
  
  def to_s
    comment
  end
  

  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  load_and_authorize_resource  

  # GET /comments
  # GET /comments.json
  def index

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment.user = current_user
    @comment.commentable = Article.find(params[:comment][:commentable_id]) if params[:comment][:commentable_type] == 'Article'
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to :back, notice: 'Comment was successfully created.' }
        format.js
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment.commentable, notice: 'Comment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :ok }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper

  def last_comments(count=5)
    comments = []
    Article.accessible_by(current_ability).each{ |a| comments +=  a.comments } #authorizing comments via articles
    comments[0..count-1]
  end
  
end

app/views/comments/_comment.html.haml
=content_tag_for :div, comment do
  = render 'comments/meta', :comment => comment
  %h4= comment.title

  .body= comment
  

app/views/comments/_compact.html.haml
- container_tag ||= :li

=content_tag container_tag do
  .commentable= comment.commentable
  .comment=     link_to comment, article_path(comment.commentable, :anchor => 'comment_'+comment.id.to_s)
  

  

app/views/comments/_form.html.haml
- comment ||= @comment
= form_for comment, :remote => true do |f|
  -if comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - comment.errors.full_messages.each do |msg|
          %li= msg
          
  = f.hidden_field :commentable_id
  = f.hidden_field :commentable_type

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :comment
    = f.text_area :comment
    
  .actions
    = f.submit 'Save'

app/views/comments/_meta.html.haml
.meta
  %ul
    %li.created-at
      created: 
      = time_ago_in_words(comment.created_at)
      ago
    %li.author
      written by: 
      = link_to comment.user, comment.user
      
    -if can? :update, comment
      %li.edit    
        = link_to 'Edit', edit_comment_path(comment)
      

app/views/comments/create.js.erb
$('div#comments').html("<%= escape_javascript(render @comment.commentable.comments) %>"); 

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', @comment.commentable

app/views/comments/index.html.haml
%h1 Listing comments

=render Comment.all

app/views/comments/new.html.haml
%h1 New comment

= render 'comments/form'

app/views/comments/show.html.haml
=render @comment