config/routes.rb
DistinctionsFines::Application.routes.draw do

  resources :authentications

    match '/signout' => 'sessions#destroy', :as => :signout
    match '/signin' => 'sessions#new', :as => :signin
    match '/users/auth/:provider/callback' => 'authentications#create'          
    match '/auth/failure' => 'sessions#failure'

  devise_for :users, :controllers => { :omniauth_callbacks => "authentications"}

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :users

  resources :articles
  
  resources :comments  
  

  root :to => 'blog#index'

end

app/models/article.rb
class Article < ActiveRecord::Base

  acts_as_commentable

  belongs_to :author, :class_name => 'User'
  
  validates :body, :presence => true

  validates :status_code, :presence => true
  
  default_scope :order => "created_at DESC"
  
  scope :published, :conditions => { :status_code => 1 }
  

  
  def body
    BlueCloth.new(super).to_html.html_safe  
  end
  
  def intro
    body.split('<!--more-->')[0]
  end
  
  def status
    if    status_code == 0
      'draft'
    elsif status_code == 1
      'published'
    end
  end
  
  def to_s
    title
  end

  def to_param 
    "#{id}-#{to_s.truncate(150).parameterize}"
  end  
  
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  load_and_authorize_resource  

  # GET /articles
  # GET /articles.json
  def index

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :ok }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper

  def last_articles(count=5)
    Article.accessible_by(current_ability).limit(count)
  end
  
end

app/views/articles/_article.html.haml
.article{:class => article.status}  
  = render 'articles/meta', :article => article  
      
  %h3.title
    - if controller.controller_name == 'blog'
      = link_to article.title, article
    -else
      = article.title

  .body
  
    - if controller.controller_name == 'blog'
      = article.intro
      = link_to 'Read >', article
      
    - else
      = article.body
      = link_to '< Back', root_path            

      .comments
        %h3 Comments
        #comments
          = render article.comments
      - if user_signed_in?
        = render 'comments/form', :comment => Comment.new(:commentable => article)
      - else
        = link_to "Sign in", new_session_path(resource_name)
        or
        = link_to "sign up", new_registration_path(resource_name)
        to discuss this article

app/views/articles/_form.html.haml
= form_for @article do |f|
  -if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :created_at
    = f.datetime_select :created_at
  .field
    = f.label :updated_at
    = f.datetime_select :updated_at
  .field
    = f.label :author_id
    = f.number_field :author_id
  .actions
    = f.submit 'Save'

app/views/articles/_meta.html.haml
.meta
  %ul
    %li.author
      written by: 
      = link_to article.author, article.author  
    %li.created-at
      created: 
      = time_ago_in_words(article.created_at)
      ago
    %li.updated-at
      updated:
      = time_ago_in_words(article.updated_at)
      ago
    %li.comments-count
      = link_to article.comments.count.to_s + pluralize(article.comments.count,'comments', 'comment'), article_path(article, :anchor => "comments")
      
    -if can? :update, article
      %li.edit    
        = link_to 'Edit', edit_article_path(article)
      

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/show.html.haml
=render @article