config/routes.rb
DistinctionsFines::Application.routes.draw do

  resources :authentications

    match '/signout' => 'sessions#destroy', :as => :signout
    match '/signin' => 'sessions#new', :as => :signin
    match '/users/auth/:provider/callback' => 'authentications#create'          
    match '/auth/failure' => 'sessions#failure'

  devise_for :users, :controllers => { :omniauth_callbacks => "authentications"}

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :users

  resources :articles
  
  resources :comments  
  

  root :to => 'blog#index'

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base

belongs_to :user


end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  # GET /authentications
  # GET /authentications.json
  
    
  def index
  @authentications = current_user.authentications if current_user

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authentications }
    end
  end

  # GET /authentications/1
  # GET /authentications/1.json
  def show
    @authentication = Authentication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @authentication }
    end
  end

  # GET /authentications/new
  # GET /authentications/new.json
  def new
    @authentication = Authentication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @authentication }
    end
  end

  # GET /authentications/1/edit
  def edit
    @authentication = Authentication.find(params[:id])
  end

  # POST /authentications
  # POST /authentications.json

  def create
  
    auth = request.env['omniauth.auth']  
    authentication = Authentication.find_or_create_by_provider_and_uid(auth['provider'], auth['uid'])
    
    if user_signed_in?
      current_user.authentications << authentication

    elsif authentication.user.present?
      sign_in(:user, authentication.user)

    else
      u = User.create(:display_name => auth['user_info']['name'], :email => auth['user_info']['email'], :password => random_pronouncable_password)
      authentication.user = u
      authentication.save
      sign_in(:user, authentication.user)
    end
    
    redirect_to authentications_path
        

  end


  # PUT /authentications/1
  # PUT /authentications/1.json
  def update
    @authentication = Authentication.find(params[:id])

    respond_to do |format|
      if @authentication.update_attributes(params[:authentication])
        format.html { redirect_to @authentication, notice: 'Authentication was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @authentication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authentications/1
  # DELETE /authentications/1.json
  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."

    respond_to do |format|
      format.html { redirect_to authentications_url }
      format.json { head :ok }
    end
  end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/_form.html.haml
= form_for @authentication do |f|
  -if @authentication.errors.any?
    #error_explanation
      %h2= "#{pluralize(@authentication.errors.count, "error")} prohibited this authentication from being saved:"
      %ul
        - @authentication.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :provider
    = f.text_field :provider
  .field
    = f.label :uid
    = f.text_field :uid
  .actions
    = f.submit 'Save'

app/views/authentications/_providers.html.haml
.providers
  %ul
    %li= link_to image_tag("facebook_64.png", :size => "64x64", :alt => "Facebook") + 'Facebook', user_omniauth_authorize_path(:facebook)
        
    -# %li= link_to image_tag("twitter_64.png" , :size => "64x64", :alt => "Twitter" ) + 'Twitter' , user_omniauth_authorize_path(:twitter)
    -# %li= link_to image_tag("google_64.png"  , :size => "64x64", :alt => "Google"  ) + 'Google'  , "/auth/google"
    -# %li= link_to image_tag("openid_64.png"  , :size => "64x64", :alt => "OpenID"  ) + 'OpenID'  , "/auth/openid"

app/views/authentications/edit.html.haml
%h1 Editing authentication

= render 'form'

= link_to 'Show', @authentication
\|
= link_to 'Back', authentications_path

app/views/authentications/index.html.haml
%h2 Your authentication options
- if @authentications
  - unless @authentications.empty?
    %p
      %h3 You can sign in to this account using
    .authentications
      - for authentication in @authentications
        .authentication
          = image_tag "#{authentication.provider}_32.png", :size => "32x32"
          .provider= authentication.provider.titleize
          .uid= authentication.uid
          = link_to "X", authentication, :confirm => 'Are you sure you want to remove this authentication option?', :method => :delete, :class => "remove"
      .clear
  %p
    %h3 Add a service to sign in with
= render 'authentications/providers'

app/views/authentications/new.html.haml
%h1 New authentication

= render 'form'

= link_to 'Back', authentications_path

app/views/authentications/show.html.haml
%p#notice= notice

%p
  %b User:
  = @authentication.user_id
%p
  %b Provider:
  = @authentication.provider
%p
  %b Uid:
  = @authentication.uid

= link_to 'Edit', edit_authentication_path(@authentication)
\|
= link_to 'Back', authentications_path